name: KurosioAuctionSystem
version: '${version}'
main: kurosio.kurosioauctionsystem.KurosioAuctionSystem
api-version: '1.15'
depend:
  - Vault

commands:
  kac:
    description: Kurosio Auction System